version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.8.0

    environment:
      TEST_REPORTS: /tmp/test-reports

    steps:
      - checkout

      - run:
          name: cd
          command: cd ./reason-graphql

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: tests
          command: yarn test
